import type { NavigationState } from "../../app/NavigationCoordinator";
import { characters, characterForRole, type CharacterId } from "../data/characters";
import { themes, type ThemeId } from "../data/themes";

export class MenuView {
  constructor(private readonly root: HTMLElement, onAction: (action: string) => void) {
    root.addEventListener("click", (event) => { const button = event.target instanceof Element ? event.target.closest<HTMLButtonElement>("[data-menu-action]") : null; if (button) onAction(button.dataset.menuAction ?? ""); });
    root.addEventListener("change", event => { if (event.target instanceof HTMLSelectElement && event.target.matches("[data-theme-select]")) onAction(`theme:${event.target.value}`); if (event.target instanceof HTMLSelectElement && event.target.matches("[data-character-select]")) onAction(`character:${event.target.value}`); });
  }
  render(state: NavigationState, mode: "rampage" | "hunt" = "rampage", themeId: ThemeId = "desert", characterId?: CharacterId, rampageAscent = true): void {
    const selected = characterForRole(mode, characterId);
    if (!selected) throw new RangeError("Invalid menu character.");
    const ascentRampage = mode === "rampage" && rampageAscent;
    let body: string;
    switch (state) {
      case "title": body = `<p class="preview__kicker">The desert is alive</p><h2>Own the breach.</h2><p>Build momentum beneath the dunes. Strike from below. Survive the response.</p>${button("enter", "Enter desert")}`; break;
      case "menu": body = `<p class="preview__kicker">Main menu</p><h2>Your next hunt.</h2>${button("play", "Play")}${button("help", "How to Play")}${button("settings", "Settings")}${button("credits", "Credits")}`; break;
      case "selection": body = `<p class="preview__kicker">Role / mode</p><h2>Choose your side.</h2><p><strong>Rampage</strong> · Burrow under the rising sand, hunt the five Hunters before they reach the rooftop RPG, and heal only from the carrion in the sand.</p>${button("choose", "Choose Rampage")}<p><strong>Rampage Classic</strong> · The older arena score chase: consume prey, break the response bands and survive.</p>${button("choose-classic", "Choose classic arena")}<p><strong>Ranger / Hunt</strong> · Climb above the rising sand, survive the worms and reach the rooftop RPG.</p>${button("choose-hunt", "Choose Hunt")}${button("menu", "Main menu")}`; break;
      case "preview": body = mode === "hunt" ? `<p class="preview__kicker">Hunt · Survival ascent</p><h2>Climb above the rising sand.</h2><p>Survive the worms and reach the rooftop RPG to finish the hunt. Watch breach warnings, shoot exposed worm regions, and keep moving upward as the hazard rises.</p><p>A/D move · Space or W jump · S drop through · Mouse aim / click fire · Q skill · Shift dodge · R reload. Touch: joystick, Fire/Aim drag, Jump, Skill, Dodge and Supply.</p>${import.meta.env.DEV ? '<label><input type="checkbox" data-ai-debug> Debug mode (practice; no records)</label>' : ""}${button("start", "Start Hunt")}${button("help", "How to Play")}${button("selection", "Change mode")}` : ascentRampage ? `<p class="preview__kicker">Rampage · Hunting the five</p><h2>They climb. You burrow.</h2><p>Five Hunter bots race the rising sand to the rooftop RPG. Reach them from below, break their climb, and eat the carrion drifting in the sand to heal - it is your only recovery here.</p><p>WASD / arrows steer · Shift or right click Burst · hold up with Burst to leap · Space skill · Left click aim / fire. Touch: joystick, Burst, Skill.</p>${import.meta.env.DEV ? '<label><input type="checkbox" data-ai-debug> Debug mode (practice; no records)</label>' : ""}${button("start", "Start Rampage")}${button("help", "How to Play")}${button("selection", "Change mode")}` : `<p class="preview__kicker">Rampage Classic · Desert frontier</p><h2>Momentum is your weapon.</h2><p>Prey restores health. Infantry locks its aim before firing. Vary your targets to build a stronger chain.</p>${button("start", "Start classic arena")}${button("help", "How to Play")}${button("selection", "Change mode")}`; break;
      case "how-to-play": body = mode === "hunt" ? `<h2>How to Play</h2><p>Climb above the rising hazard. Reach the rooftop crate, then defeat the boss with your RPG.</p><p>A/D move; Space, W or Up jump; S or Down drop through. Mouse aims and fires, R reloads, Q uses ${selected.skill.name}, Shift dodges. Touch random supply crates for one skill from another Hunter; E / gamepad X / Supply uses it once. A full slot leaves the crate available.</p><p>${selected.skill.description} Normal worms return after 10 seconds. Boss immunity lasts 3 seconds; wait for the shield to fade.</p><p>Touch uses independent movement, Fire/Aim, Jump, Skill and Dodge.</p>${button("close", "Back")}` : ascentRampage ? `<h2>How to Play</h2><p>You are the worm. Five Hunter bots climb the tower as the sand rises; each one that reaches the rooftop crate arms an RPG. Break them on the way up.</p><p><strong>Move:</strong> WASD / arrows, left stick, or touch joystick. <strong>Burst:</strong> Shift, right click, or touch Burst - hold up while bursting to leap out of the sand. <strong>Skill:</strong> Space or touch ${selected.skill.name}.</p><p>${selected.skill.description} Your only healing is carrion drifting in the sand: swim into it with your mouth. Diving out of sight stops them shooting.</p>${button("close", "Back")}` : `<h2>How to Play</h2><p><strong>Move:</strong> WASD / arrows, left stick, or touch joystick.</p><p><strong>Skill:</strong> Space / right trigger / touch ${selected.skill.name}. <strong>Burst:</strong> Shift / right bumper / touch Burst. <strong>Pause:</strong> Escape / Start / Pause.</p><p>Turn upward underground to breach. Consume prey for health, strike infantry with speed or mouth contact, and re-enter to avoid shots. Aim-lock circles announce danger. Combo grace lasts three seconds, followed by a visible fading warning.</p>${button("close", "Back")}`; break;
      case "credits": body = `<h2>Credits</h2><p>Sandstrike · Original procedural art, character animation, generated audio and game code.</p><p>Built with Phaser, TypeScript and Vite. Mechanical reference research is documented in the repository. No copied branding, art or audio is shipped.</p>${button("close", "Back")}`; break;
      default: body = "";
    }
    if (state === "preview") body = `<div class="loadout-selectors"><label class="theme-choice">Environment<select aria-label="Environment" data-theme-select>${Object.entries(themes).map(([id, theme]) => `<option value="${id}"${id === themeId ? " selected" : ""}>${theme.name}</option>`).join("")}</select></label><label class="theme-choice">Character<select aria-label="Character" data-character-select>${characters.filter(c => c.role === selected.role).map(c => `<option value="${c.id}"${c.id === selected.id ? " selected" : ""}>${c.name}</option>`).join("")}</select></label></div><p class="character-description" data-character-description><strong>${selected.skill.name}</strong> · ${selected.skill.description} Cooldown ${String(selected.skill.cooldownTicks / 60)}s.${selected.weapon ? ` Starting weapon: ${selected.weapon.name}.` : ""}</p>${body}`;
    if (state === "preview" && mode === "rampage" && import.meta.env.DEV) body += '<label><input type="checkbox" data-ai-debug> Debug mode</label>';
    this.root.innerHTML = body; this.root.hidden = body === "";
    this.root.querySelector("h2")?.setAttribute("id", "preview-title");
    queueMicrotask(() => this.root.querySelector<HTMLButtonElement>("button")?.focus());
  }
}
function button(action: string, label: string): string { return `<button type="button" class="menu-action" data-menu-action="${action}">${label}</button>`; }
